[manifest]
id = "minigame_reset"
version = "1.0.0"
display_name = "Minigame Reset"
description = "Lets you reset a minigame (Jetpac, banana barrel bonus games, Minecart Mayhem) on failure or with a button combo, with a 3-2-1-GO countdown, skipping fail/outro cutscenes. A second combo instantly wins bonus barrels/Minecart Mayhem"
short_description = "Reset or instant-win minigames with button combos, with a 3-2-1-GO countdown on reset"
authors = [ "cdalong" ]
game_id = "dk64"
minimum_recomp_version = "1.0.0"

[inputs]
elf_path = "build/mod.elf"
mod_filename = "minigame_reset"
func_reference_syms_file = "Dk64Syms/dump.toml"
data_reference_syms_files = [ "Dk64Syms/data_dump.toml" ]
additional_files = ["thumb.dds"]
